import "./globals.css";
import AppWrapper from "./store/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="background">
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
