import "./globals.css";
import AppWrapper from "./store/store";
import { Geologica } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geologica = Geologica({subsets : ["latin"], weight : ["100", "200", "600"]});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geologica.className} background`}>
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
